### ISSUE TITLE
Link PTX assemblas

### ISSUE THREAD

**Issue by termoshtt** [termoshtt/accel#2]
rust2ptx crate compiles Rust to PTX using `xargo rustc` command, which compiles only `lib.rs`. To avoid undefined reference, accel-core uses `#[inline(always)]`, but it should be bad :<

**Comment by denzp** [comment]
I think an experimental external linker [rust-ptx-linker](https://github.com/denzp/rust-ptx-linker) I've implemented some time ago might be useful here. 

Unfortunately, it's an extra dependency, which is not good... But it can help to build libs with dependencies and without `#[inline(always)]`.

**Comment by termoshtt** [comment]
Great, I'm creating same one at https://github.com/termoshtt/cargo-nvbuild
I think we should copy `librustc_trans/back/bytecode.rs` into this crate to avoid using `#[feature(rustc_private)]`. It does not depends on other parts of `librustc_trans`.
