### ISSUE TITLE
Maintenance accel

### ISSUE THREAD

**Issue by termoshtt** [termoshtt/accel#57]
Unfortunately, I have a little time to manage this project. I'd like to seek anyone interested in managing/developing this project.

**Comment by eisterman** [comment]
The project has actually a maintainer or it's dead?

**Comment by termoshtt** [comment]
Actually, this project has been dead. Some functionality has been inherited to [rust-cuda/cuda-sys](https://github.com/rust-cuda/cuda-sys), and other projects started:

- https://github.com/bheisler/RustaCUDA
- https://github.com/denzp/rust-ptx-builder

I am working from yesterday to restart this project. I will devote my new-year holiday for it, but potentially it still be hard to keep this project.

**Comment by eisterman** [comment]
If there is something simple I can do to help use the "good first issue" label and I will try to do what I can

**Comment by jon-chuang** [comment]
@termoshtt 
Hi, I'd like to become the maintainer for this project. As I would like to get merges and have many plans for many new features, including async/await, module-level compilation, generalisations to more types than just scalars (general structs, maybe arrays), and also abstractions for load balancing between CPU and GPU, maybe using some work stealing concepts, maybe building on Rayon. If I get an affirmative, I can show my progress in a few weeks to get the green light that I should be the new maintainer. 

However, I have received no replies recently. Hopefully I can get a reply here.
