### ISSUE TITLE
volatile: is there a way to mark an argument volatile ?

### ISSUE THREAD

**Issue by zeroexcuses** [termoshtt/accel#59]
See last slide of https://developer.download.nvidia.com/assets/cuda/files/reduction.pdf

Is there a way to mark a field volatile in rust-accel ?

**Comment by termoshtt** [comment]
I do not have enough answer.
As far as I googled, [volatile crate](https://docs.rs/volatile/0.2.5/volatile/) can mark pointer to be volatile, and LLVM will lower its IR into `{ld,st}.volatile`, but I have not try it.
https://docs.nvidia.com/cuda/nvvm-ir-spec/index.html#volatile-memory-access

You may get more info on [rust-cuda/wg](https://github.com/rust-cuda/wg).
